[cursor]
shape = 'beam'

theme = "tokionight"
blinking-cursor = false
option-as-alt = 'left'

[fonts]
family = "ComicShannsMono Nerd Font"
size = 22


[keyboard]
use-kitty-keyboard-protocol = true
disable-ctlseqs-alt = false


[navigation]
mode = "NativeTab"
clickable = true
use-current-path = false
color-automation = []

[colors]
cursor = '#0BA95B' 

[renderer]
performance = "High"
backend = "Metal"
disable-unfocused-render = false


[window]
width = 600
height = 400
mode = "Windowed"
#opacity = 0.5
opacity = 1.0
blur = true
decorations = "Disabled"
