cursor = '|'
theme = "tokyonight"
editor = '/opt/homebrew/bin/nvim'
blinking-cursor = false

[fonts]
family = "ComicShannsMono Nerd Font"
size = 20



[keyboard]
use-kitty-keyboard-protocol = false
disable-ctlseqs-alt = false


[navigation]
mode = "NativeTab"
clickable = true
use-current-path = false
color-automation = []

[colors]
cursor = '#0BA95B' 

[renderer]
performance = "High"
backend = "Metal"
disable-unfocused-render = false
