[cursor]
shape = 'beam'

[colors]
background = '#1e1e2e'
foreground = '#cdd6f4'
selection-background = '#585b70'
selection-foreground = '#cdd6f4'
cursor = '#f5e0dc'
black = '#45475a'
red = '#f38ba8'
green = '#a6e3a1'
yellow = '#f9e2af'
blue = '#89b4fa'
magenta = '#f5c2e7'
cyan = '#94e2d5'
white = '#a6adc8'
light_black = '#585b70'
light_red = '#f37799'
light_green = '#89d88b'
light_yellow = '#ebd391'
light_blue = '#74a8fc'
light_magenta = '#f2aede'
light_cyan = '#6bd7ca'
light_white = '#bac2de'

blinking-cursor = false
option-as-alt = 'left'

[fonts]
#family = "ComicShannsMono Nerd Font"
family = "Mononoki Nerd Font"
size = 22


[keyboard]
use-kitty-keyboard-protocol = true
disable-ctlseqs-alt = true


[navigation]
mode = "NativeTab"
clickable = true
use-current-path = false
color-automation = []

[renderer]
performance = "High"
backend = "Metal"
disable-unfocused-render = false


[window]
width = 600
height = 400
mode = "Windowed"
#opacity = 0.5
opacity = 1.0
blur = true
decorations = "Disabled"
